# Generated by Django 5.1.7 on 2025-03-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Customer_address',
            new_name='customer_address',
        ),
    ]
