# Generated by Django 5.1.7 on 2025-03-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker'), ('farmer', 'External Farmer'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('consumer', 'Consumer')], default='farmer', max_length=20),
        ),
    ]
