# Generated by Django 5.1.7 on 2025-04-04 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rental', 'Pond Rental'), ('sales', 'Fish Sales')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction', models.CharField(help_text='Related transactoin ID or reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage for pond rentals', max_digits=5)),
                ('sales_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage for fish sales', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_details', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=0, max_digits=20)),
                ('width', models.DecimalField(decimal_places=0, max_digits=20)),
                ('heigth', models.DecimalField(decimal_places=1, max_digits=20)),
                ('location', models.CharField(max_length=100)),
                ('rental_price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance')], default='available', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('medication', 'Medication'), ('maintenance', 'Maintenance'), ('fingerlings', 'Fingerlings'), ('others', 'Others')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('recorded_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('insurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='farmer_dashboard.insurancepackage')),
            ],
        ),
        migrations.CreateModel(
            name='PondRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_rentals', to=settings.AUTH_USER_MODEL)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='farmer_dashboard.pond')),
            ],
        ),
        migrations.CreateModel(
            name='FishGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_growth/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='fish_growth/videos/')),
                ('size_in_cm', models.DecimalField(decimal_places=2, help_text='Fish size in cm', max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='farmer_dashboard.pondrental')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='farmer_dashboard.pondrental')),
            ],
        ),
    ]
