# Generated by Django 5.1.7 on 2025-03-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_growth/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='fish_growth/videos/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('size_in_cm', models.DecimalField(decimal_places=2, help_text='Fish size in cm', max_digits=5)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='farmer_dashboard.pondrental')),
            ],
        ),
    ]
